FROM golang:latest
ENV GO111MODULE=on
WORKDIR /go-starter

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -log-prefix=false -command=./go-starter
