# syntax=docker/dockerfile:1

FROM golang:1.23-alpine
#ENV GO111MODULE=on
WORKDIR /api

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./
EXPOSE 5000

RUN go install -mod=mod github.com/githubnemo/CompileDaemon

ENTRYPOINT exec CompileDaemon --build="go build -o /api" --command=."/api"
